# Generated by Django 2.2 on 2020-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200816_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='result',
            name='correct_option',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
