# Generated by Django 2.2 on 2020-08-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_result_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='result',
            name='participant_id',
        ),
    ]
