# Generated by Django 2.2 on 2020-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20200819_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='participant_id',
            field=models.IntegerField(),
        ),
    ]
