# Generated by Django 2.2 on 2020-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200820_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
