# Generated by Django 2.2 on 2020-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200820_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(blank=True, null=True)),
                ('questions_numbers', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('exams_ended', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_quiz_numbers', models.IntegerField(blank=True, null=True)),
                ('exam_hours', models.IntegerField(blank=True, null=True)),
                ('exam_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
