# Generated by Django 2.2 on 2020-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_monitor_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='maximum_quiz_numbers',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
