# Generated by Django 2.2 on 2020-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20200821_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='questions_numbers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
