# Generated by Django 2.2 on 2020-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20200821_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
