# Generated by Django 2.2 on 2020-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200824_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
