# Generated by Django 2.2 on 2020-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_auto_20200824_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='percentage',
            field=models.IntegerField(blank=True),
        ),
    ]
