# Generated by Django 2.2 on 2020-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20200824_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='exam_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True),
        ),
    ]
