# Generated by Django 2.2 on 2020-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_monitor_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='exam_hours',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
