# Generated by Django 2.2 on 2020-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_auto_20200825_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='exam_hours',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
