# Generated by Django 2.2 on 2020-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_auto_20200825_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
