# Generated by Django 2.2 on 2020-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_auto_20200825_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='begin',
            field=models.BooleanField(default=False),
        ),
    ]
